# Redirect HTTP traffic to HTTPS
server {
    listen 80;
    server_name frontend backend;

    return 301 https://$host$request_uri;
}

# backend Server Block
server {
    listen 443 ssl;
    server_name backend; # Replace with your backend domain

    ssl_certificate /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;

    root /var/www/html/backend/public;

    index index.php index.html;

    error_log  /var/log/nginx/backend_error.log;
    access_log /var/log/nginx/backend_access.log;

    location / { # No rewrite needed here
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php-fpm-backend:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}

# Frontend Server Block
server {
    listen 443 ssl;
    server_name frontend;

    ssl_certificate /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;

    root /var/www/html/frontend/public;

    index index.php index.html;

    error_log  /var/log/nginx/frontend_error.log;
    access_log /var/log/nginx/frontend_access.log;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include fastcgi_params;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass php-fpm-frontend:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location ~ /\.ht {
        deny all;
    }
}

# Golang API Server Block (https://product)
server {
    listen 443 ssl;
    server_name product;

    ssl_certificate /etc/nginx/certs/selfsigned.crt;
    ssl_certificate_key /etc/nginx/certs/selfsigned.key;

    error_log  /var/log/nginx/product_error.log;
    access_log /var/log/nginx/product_access.log;

    location / {
        proxy_pass http://php-fpm-product:9000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}